image: Visual Studio 2022
environment:
  matrix:
    - GO: "C:\go113"
    - GO: "C:\go112"
    - GO: "C:\go111"
    - GO: "C:\go110"
build: off
install:
  - "%GO%\\go.exe mod download"
test_script:
  - "%GO%\\go.exe test"
