image: Visual Studio 2022
environment:
  matrix:
    - GO: "C:\\go113\\bin"
    - GO: "C:\\go112\\bin"
    - GO: "C:\\go111\bin"
    - GO: "C:\\go110\\bin"
build: off
install:
  - "%GO%\\go.exe mod download"
test_script:
  - "%GO%\\go.exe test"
